# Generated by Django 6.0.6 on 2026-06-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL')], max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('database_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_connections', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_tables', to='company.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='data_sources.databaseconnection')),
            ],
            options={
                'unique_together': {('connection', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=100)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='data_sources.datatable')),
            ],
            options={
                'unique_together': {('table', 'column_name')},
            },
        ),
        migrations.CreateModel(
            name='TablePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_query', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_permissions', to='company.companymember')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='data_sources.datatable')),
            ],
            options={
                'unique_together': {('member', 'table')},
            },
        ),
    ]
